# Generated by Django 4.2.5 on 2023-09-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='username',
        ),
    ]
