# Generated by Django 4.2.5 on 2023-10-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_email_register_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
