# Generated by Django 4.2.5 on 2023-10-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='qpointlogin',
        ),
    ]
